### ISSUE TITLE
nodes not responding

### ISSUE THREAD

**Issue by cogweg** [namgk/node-red-contrib-firebase-realtime-database#15]
Hello, I tried to use your contribution, but cannot get it working.  
In node-red, I do not see any log or debug entry. With other nodered contributions, I could get firebase database commands GET, PUSH, etc. running.
Thanks for help,
C

**Comment by namgk** [comment]
Could be that the firebase admin sdk was outdated. I just updated the node. Sorry for the delay.

Thanks
