### ISSUE TITLE
Steps to include in project inside

### ISSUE THREAD

**Issue by bigdoods** [namgk/node-red-contrib-firebase-realtime-database#3]
Steps to include in project:
1. npm --save namgk/node-red-contrib-firebase-realtime-database#master
2. cd node_modules/node-red-contrib-firebase-realtime-database/test
2. touch my-firebase-service-credential.json
3. Firebase console > project settings > service accounts > create new private key. Then copy contents to my-firebase-service-credential.json
4. npm run test
5. cd to project top level
6. node index.js

Notes:
* Will get data from Firebase Realtime Database NOT FIRESTORE (For firestore use: https://github.com/Sichangi/node-red-contrib-cloud-firestore)
* Example Database Ref: /76/-LfLoVaQopk3ZUUL3lEp

**Comment by namgk** [comment]
Hi,

I’m sorry, I’m not sure I get your question?

Could you please reiterate?

Thanks

**Comment by bigdoods** [comment]
Apologies. Not an issue just some more extensive setup comments that might help bridge the gap for some newer programmers than you and I that find this. Feel free to close and copy paste to readme or delete 😀

**Comment by anuragvermaa** [comment]
Thanks for taking your time to explain it. 
Saved a lot of effort and confusion.
