### ISSUE TITLE
Getting data from Realtime database to NodeRed Chart Dashboard

### ISSUE THREAD

**Issue by paolo0926** [namgk/node-red-contrib-firebase-realtime-database#4]
Hi, I can't seem to get the data from my Realtime database to the NodeRed Chart. I don't know what I'm doing wrong. Please help.

![2019-05-27 15_58_55-Window](https://user-images.githubusercontent.com/40094551/58404749-72bec500-8098-11e9-9bb2-13bba51b762b.png)
![2019-05-27 15_59_26-Window](https://user-images.githubusercontent.com/40094551/58404752-73575b80-8098-11e9-8581-3a9bc8deeb62.png)

**Comment by namgk** [comment]
Hi,

Does it output to a debug node?
